[build]
# source: https://doc.rust-lang.org/rustc/platform-support.html

# windows
## 32 bit
target = "i686-pc-windows-msvc"
# target = "i686-pc-windows-gnu"

## 64 bit
# target = "x86_64-pc-windows-msvc"
# target = "x86_64-pc-windows-gnu"


# linux
## 32 bit
# target = "i686-unknown-linux-gnu"

## 64 bit
# target = "x86_64-unknown-linux-gnu"

